(function(){"use strict";
const cfg=window.SITE_CONFIG.supabase;
const sb=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const statusLabels={new:"Нове",awaiting_payment:"Очікує оплату",paid:"Оплачено",shipped:"Відправлено",completed:"Виконано",cancelled:"Скасовано"};
let orders=[],reviews=[],activeOrder=null;
const $=s=>document.querySelector(s);const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));const money=v=>`${Number(v||0).toLocaleString("uk-UA",{maximumFractionDigits:2})} грн`;const date=v=>new Intl.DateTimeFormat("uk-UA",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));
function toast(text){const el=document.createElement("div");el.className="admin-toast";el.textContent=text;document.body.appendChild(el);setTimeout(()=>el.remove(),2800)}
async function requireAdmin(){const {data:{user}}=await sb.auth.getUser();if(!user)return false;const {data,error}=await sb.from("admin_users").select("user_id,email").eq("user_id",user.id).maybeSingle();if(error||!data){await sb.auth.signOut();throw new Error("Цей акаунт не має доступу до адмін-панелі.");}$("#adminIdentity").textContent=data.email;return true;}

function showLogin(message=""){$("#loginView").hidden=false;$("#dashboardView").hidden=true;$("#logoutBtn").hidden=true;$("#loginMessage").textContent=message;}

function showDashboard(){ $("#loginView").hidden=true;$("#loginMessage").textContent="";$("#dashboardView").hidden=false;$("#logoutBtn").hidden=false;window.scrollTo({top:0,behavior:"auto"});}
async function loadAll(){document.body.classList.add("admin-loading");try{const [o,r]=await Promise.all([sb.from("orders").select("*").order("created_at",{ascending:false}).limit(500),sb.from("reviews").select("*").order("created_at",{ascending:false}).limit(500)]);if(o.error)throw o.error;if(r.error)throw r.error;orders=o.data||[];reviews=r.data||[];renderOrders();renderReviews();}finally{document.body.classList.remove("admin-loading");}}

function renderStats(){
  const counts={new:0,awaiting_payment:0,paid:0,shipped:0};
  orders.forEach(o=>{if(counts[o.status]!==undefined)counts[o.status]++});
  $("#ordersStats").innerHTML=Object.entries(counts).map(([s,n])=>`<div class="admin-stat"><strong>${n}</strong><span>${statusLabels[s]}</span></div>`).join("");
  $("#ordersBadge").textContent=orders.filter(o=>["new","awaiting_payment"].includes(o.status)).length||"";
  const now=new Date(),startDay=new Date(now.getFullYear(),now.getMonth(),now.getDate()),startWeek=new Date(startDay);startWeek.setDate(startDay.getDate()-6);const startMonth=new Date(now.getFullYear(),now.getMonth(),1);
  const periods=[["Сьогодні",startDay],["7 днів",startWeek],["Цей місяць",startMonth]];
  $("#periodStats").innerHTML=periods.map(([label,start])=>{const rows=orders.filter(o=>new Date(o.created_at)>=start&&o.status!=="cancelled");const total=rows.reduce((sum,o)=>sum+Number(o.total_amount||0),0);return `<article class="admin-period-card"><span>${label}</span><strong>${money(total)}</strong><small>${rows.length} замовлень</small></article>`}).join("");
  renderChart();
}

function renderChart(){const days=[];for(let i=29;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);days.push({date:d,total:0})}orders.filter(o=>o.status!=="cancelled").forEach(o=>{const d=new Date(o.created_at);d.setHours(0,0,0,0);const day=days.find(x=>x.date.getTime()===d.getTime());if(day)day.total+=Number(o.total_amount||0)});const max=Math.max(1,...days.map(d=>d.total));$("#salesChart").innerHTML=days.map(d=>`<div class="admin-chart__bar" style="--bar-height:${Math.max(2,d.total/max*100)}%"><span>${d.date.toLocaleDateString("uk-UA",{day:"2-digit",month:"2-digit"})}: ${money(d.total)}</span></div>`).join("");$("#chartTotal").textContent=money(days.reduce((s,d)=>s+d.total,0));}

function renderOrders(){renderStats();const q=$("#orderSearch").value.trim().toLowerCase(),filter=$("#orderStatusFilter").value;const list=orders.filter(o=>(!filter||o.status===filter)&&(!q||[o.client_order_id,o.customer_name,o.customer_phone,o.customer_email,o.customer_city,o.delivery_details].join(" ").toLowerCase().includes(q)));$("#ordersEmpty").hidden=!!list.length;$("#ordersList").innerHTML=list.map(o=>`<article class="admin-card admin-order-card" data-order="${esc(o.id)}"><div><div class="admin-card__title">${esc(o.client_order_id)}</div><div class="admin-card__meta">${date(o.created_at)}</div><div class="admin-quick-status">${o.status==="new"?`<button data-quick-status="awaiting_payment">До оплати</button>`:""}${!["paid","shipped","completed","cancelled"].includes(o.status)?`<button data-quick-status="paid">Оплачено</button>`:""}${o.status==="paid"?`<button data-quick-status="shipped">Відправлено</button>`:""}${o.status==="shipped"?`<button data-quick-status="completed">Виконано + відгук</button>`:""}</div></div><div><div>${esc(o.customer_name)}</div><div class="admin-card__meta">${esc(o.customer_phone)} · ${esc(o.customer_city)}</div></div><span class="status-pill status-${esc(o.status)}">${esc(statusLabels[o.status]||o.status)}</span><div class="admin-card__amount">${money(o.total_amount)}</div></article>`).join("");document.querySelectorAll("[data-order]").forEach(el=>el.addEventListener("click",()=>openOrder(el.dataset.order)));document.querySelectorAll("[data-quick-status]").forEach(btn=>btn.addEventListener("click",e=>{e.stopPropagation();quickStatus(btn.closest("[data-order]").dataset.order,btn.dataset.quickStatus)}));}

async function quickStatus(id,status){const order=orders.find(o=>String(o.id)===String(id));if(!order)return;const old=order.status;const payload={status};if(status==="paid")payload.payment_status="paid";const {data,error}=await sb.from("orders").update(payload).eq("id",id).select().single();if(error)return toast("Помилка: "+error.message);Object.assign(order,data);renderOrders();toast("Статус змінено");if(old!==status)sb.functions.invoke("send-status-email",{body:{client_order_id:order.client_order_id}}).then(({error})=>{if(error)toast("Лист клієнту не надіслано")});}

function renderReviews(){const q=$("#reviewSearch").value.trim().toLowerCase(),filter=$("#reviewStatusFilter").value;const list=reviews.filter(r=>(!filter||r.status===filter)&&(!q||[r.product_slug,r.customer_name,r.review_text].join(" ").toLowerCase().includes(q)));$("#reviewsBadge").textContent=reviews.filter(r=>r.status==="pending").length||"";$("#reviewsAdminEmpty").hidden=!!list.length;$("#reviewsAdminList").innerHTML=list.map(r=>`<article class="admin-card review-admin-card"><div>${r.photo_url?`<img class="review-admin-card__photo" src="${esc(r.photo_url)}" alt="Фото до відгуку" loading="lazy">`:""}<div class="review-admin-card__stars">${"★".repeat(Number(r.rating)||0)}${"☆".repeat(5-(Number(r.rating)||0))}</div><div class="admin-card__title">${esc(r.product_slug)} · ${esc(r.customer_name)}</div><p>${esc(r.review_text)}</p><div class="admin-card__meta">${date(r.created_at)} · ${esc(r.status)}${r.verified_purchase?" · Перевірена покупка":""}</div></div><div class="review-admin-card__actions">${r.status!=="approved"?`<button class="btn btn-primary btn-small" data-review-action="approved" data-review-id="${r.id}">Схвалити</button>`:""}${r.status!=="rejected"?`<button class="btn btn-secondary btn-small" data-review-action="rejected" data-review-id="${r.id}">Відхилити</button>`:""}</div></article>`).join("");document.querySelectorAll("[data-review-action]").forEach(b=>b.addEventListener("click",()=>moderateReview(b.dataset.reviewId,b.dataset.reviewAction)));}
async function moderateReview(id,status){const {error}=await sb.from("reviews").update({status}).eq("id",id);if(error)return toast("Помилка: "+error.message);const row=reviews.find(r=>String(r.id)===String(id));if(row)row.status=status;renderReviews();toast(status==="approved"?"Відгук схвалено":"Відгук відхилено");}

function openOrder(id){
activeOrder=orders.find(o=>String(o.id)===String(id));if(!activeOrder)return;const items=Array.isArray(activeOrder.items)?activeOrder.items:[];$("#orderDialogContent").innerHTML=`<div class="admin-dialog__body"><div class="admin-dialog__head"><div><p class="eyebrow">Замовлення</p><h2>${esc(activeOrder.client_order_id)}</h2><p class="admin-card__meta">${date(activeOrder.created_at)}</p></div><strong>${money(activeOrder.total_amount)}</strong></div><div class="admin-detail-grid"><div class="admin-detail"><span>Клієнт</span>${esc(activeOrder.customer_name)}</div><div class="admin-detail"><span>Телефон</span><a href="tel:${esc(activeOrder.customer_phone)}">${esc(activeOrder.customer_phone)}</a></div><div class="admin-detail"><span>Email</span><a href="mailto:${esc(activeOrder.customer_email)}">${esc(activeOrder.customer_email)}</a></div><div class="admin-detail"><span>Доставка</span>${esc(activeOrder.customer_city)}, ${esc(activeOrder.delivery_details)}</div><div class="admin-detail"><span>Запрошення на відгук</span>${activeOrder.review_invitation_sent_at?`Надіслано ${date(activeOrder.review_invitation_sent_at)}`:"Ще не надсилалося"}</div></div><div class="admin-items">${items.map(i=>`<div class="admin-item"><span>${esc(i.name)} × ${esc(i.quantity)}${Array.isArray(i.selections)&&i.selections.length?`<small>Обрано: ${i.selections.map(esc).join(" · ")}</small>`:""}</span><strong>${money(i.line_total)}</strong></div>`).join("")}</div><div class="admin-actions"><label class="admin-field">Статус<select id="editStatus">${Object.entries(statusLabels).map(([v,l])=>`<option value="${v}" ${activeOrder.status===v?"selected":""}>${l}</option>`).join("")}</select></label><label class="admin-field">Статус оплати<select id="editPayment"><option value="unpaid" ${activeOrder.payment_status==="unpaid"?"selected":""}>Не оплачено</option><option value="verification" ${activeOrder.payment_status==="verification"?"selected":""}>Перевіряємо</option><option value="paid" ${activeOrder.payment_status==="paid"?"selected":""}>Оплачено</option><option value="refunded" ${activeOrder.payment_status==="refunded"?"selected":""}>Повернення</option></select></label><label class="admin-field">ТТН<input id="editTracking" value="${esc(activeOrder.tracking_number||"")}" placeholder="Номер ТТН"></label><label class="admin-field">Коментар адміністратора<textarea id="editNote">${esc(activeOrder.admin_note||"")}</textarea></label><div class="admin-actions__buttons"><button id="saveOrderBtn" class="btn btn-primary" type="button">Зберегти зміни</button></div></div></div>`;$("#saveOrderBtn").addEventListener("click",saveOrder);$("#orderDialog").showModal();}
const openOrderPaymentBase=openOrder;
openOrder=function(id){openOrderPaymentBase(id);const actions=$(".admin-actions");if(!actions||!activeOrder)return;const label=document.createElement("label");label.className="admin-field";label.innerHTML=`Спосіб оплати<select id="editPaymentMethod"><option value="bank_transfer" ${activeOrder.payment_method!=="cash_on_delivery"?"selected":""}>На рахунок</option><option value="cash_on_delivery" ${activeOrder.payment_method==="cash_on_delivery"?"selected":""}>При отриманні</option></select>`;actions.insertBefore(label,actions.children[2]||null);label.querySelector("select").addEventListener("change",async e=>{const {error}=await sb.from("orders").update({payment_method:e.target.value}).eq("id",activeOrder.id);if(error)return toast("Не вдалося змінити спосіб оплати");activeOrder.payment_method=e.target.value;toast("Спосіб оплати змінено")})};

async function saveOrder(){
const payload={status:$("#editStatus").value,payment_status:$("#editPayment").value,tracking_number:$("#editTracking").value.trim()||null,admin_note:$("#editNote").value.trim()||null};const oldStatus=activeOrder.status;const {data,error}=await sb.from("orders").update(payload).eq("id",activeOrder.id).select().single();if(error)return toast("Помилка: "+error.message);Object.assign(activeOrder,data);renderOrders();$("#orderDialog").close();toast("Замовлення оновлено");if(payload.status!==oldStatus){const {error:fnError}=await sb.functions.invoke("send-status-email",{body:{client_order_id:activeOrder.client_order_id}});if(fnError)toast("Статус збережено, але лист не надіслано");else toast("Клієнту надіслано лист");}}

function bind(){
 $("#loginForm").addEventListener("submit",async e=>{e.preventDefault();$("#loginMessage").textContent="Входимо…";const email=e.target.email.value.trim(),password=e.target.password.value;const {error}=await sb.auth.signInWithPassword({email,password});if(error)return showLogin("Помилка входу: "+error.message);try{await requireAdmin();showDashboard();await loadAll();}catch(err){showLogin(err.message);}});$("#logoutBtn").addEventListener("click",async()=>{await sb.auth.signOut();showLogin();});$("#refreshBtn").addEventListener("click",loadAll);["#orderSearch","#orderStatusFilter"].forEach(s=>$(s).addEventListener("input",renderOrders));["#reviewSearch","#reviewStatusFilter"].forEach(s=>$(s).addEventListener("input",renderReviews));document.querySelectorAll("[data-tab]").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll("[data-tab]").forEach(b=>b.classList.toggle("is-active",b===btn));$("#ordersTab").hidden=btn.dataset.tab!=="orders";$("#reviewsTab").hidden=btn.dataset.tab!=="reviews";}));}
document.addEventListener("DOMContentLoaded",async()=>{bind();const {data:{session}}=await sb.auth.getSession();if(!session)return showLogin();try{await requireAdmin();showDashboard();await loadAll();}catch(err){showLogin(err.message);}});
})();
