(function(){"use strict";
const labels={new:"Нове",awaiting_payment:"Очікує оплату",paid:"Оплачено",shipped:"Відправлено",completed:"Виконано",cancelled:"Скасовано"};
const steps=["new","paid","shipped","completed"];
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function money(v){return `${Number(v||0).toLocaleString("uk-UA",{maximumFractionDigits:2})} грн`;}
function statusIndex(status){if(status==="awaiting_payment")return 0;return Math.max(0,steps.indexOf(status));}
function render(order){const result=document.getElementById("orderTrackResult");const idx=statusIndex(order.status);const items=Array.isArray(order.items)?order.items:[];result.innerHTML=`<div class="track-head"><div><p class="eyebrow">Номер замовлення</p><h2>${esc(order.client_order_id)}</h2></div><span class="status-pill status-${esc(order.status)}">${esc(labels[order.status]||order.status)}</span></div><div class="track-timeline">${steps.map((s,i)=>`<div class="track-step ${i<=idx&&order.status!=="cancelled"?"is-done":""}">${labels[s]}</div>`).join("")}</div>${order.status==="cancelled"?'<p class="order-track__message">Замовлення скасовано. Для уточнення зверніться до VA HOME.</p>':""}<div class="track-order-lines">${items.map(item=>`<div class="track-line"><span>${esc(item.name)} × ${esc(item.quantity)}${Array.isArray(item.selections)&&item.selections.length?`<small>Обрано: ${item.selections.map(esc).join(" · ")}</small>`:""}</span><strong>${money(item.line_total)}</strong></div>`).join("")}</div><div class="track-total"><span>Сума</span><span>${money(order.total_amount)}</span></div>${order.tracking_number?`<div class="track-ttn"><small>ТТН Нової пошти</small><p><strong>${esc(order.tracking_number)}</strong></p></div>`:""}`;result.hidden=false;}
document.addEventListener("DOMContentLoaded",()=>{const form=document.getElementById("orderTrackForm"),msg=document.getElementById("orderTrackMessage"),result=document.getElementById("orderTrackResult");form.addEventListener("submit",async e=>{e.preventDefault();msg.textContent="Перевіряємо…";result.hidden=true;const orderNumber=form.elements.orderNumber.value.trim().toUpperCase(),phoneLast4=form.elements.phoneLast4.value.replace(/\D/g,"");if(phoneLast4.length!==4){msg.textContent="Введіть останні 4 цифри телефону.";return;}try{const rows=await window.VAHomeSupabase.getPublicOrderStatus(orderNumber,phoneLast4);if(!rows||!rows.length){msg.textContent="Замовлення не знайдено. Перевірте номер і цифри телефону.";return;}msg.textContent="";render(rows[0]);}catch(err){msg.textContent="Не вдалося перевірити статус. Спробуйте трохи пізніше.";}});});
})();
