-- Run once in Supabase SQL Editor to save website orders.
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  client_order_id text not null unique,
  customer_name text not null,
  customer_phone text not null,
  customer_city text not null,
  delivery_method text not null default 'Нова пошта',
  delivery_details text not null,
  customer_comment text,
  items jsonb not null,
  total_amount numeric(10,2) not null check (total_amount >= 0),
  status text not null default 'new' check (status in ('new','confirmed','sent','completed','cancelled')),
  source text not null default 'website',
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;
grant insert on table public.orders to anon, authenticated;
grant usage, select on sequence public.orders_id_seq to anon, authenticated;

drop policy if exists "Anyone can submit a website order" on public.orders;
create policy "Anyone can submit a website order"
on public.orders for insert to anon, authenticated
with check (
  status = 'new'
  and source = 'website'
  and char_length(customer_name) between 2 and 100
  and char_length(customer_phone) between 7 and 30
  and jsonb_array_length(items) between 1 and 30
  and total_amount >= 0
);

-- No SELECT policy is created: public visitors cannot read orders.
