-- VA HOME v4: migrate the existing orders table and enable website checkout.
-- Run once in Supabase SQL Editor BEFORE uploading v4 to GitHub.

do $$
begin
  if to_regclass('public.orders') is null then
    create table public.orders (
      id bigint generated by default as identity primary key,
      client_order_id text not null unique,
      customer_name text not null,
      customer_phone text not null,
      customer_email text,
      customer_city text not null,
      delivery_method text not null default 'Нова пошта',
      delivery_details text not null,
      customer_comment text,
      items jsonb not null,
      total_amount numeric(10,2) not null check (total_amount >= 0),
      status text not null default 'new',
      source text not null default 'website',
      created_at timestamptz not null default now()
    );
  else
    if exists (select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name='phone')
       and not exists (select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name='customer_phone') then
      alter table public.orders rename column phone to customer_phone;
    end if;
    if exists (select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name='city')
       and not exists (select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name='customer_city') then
      alter table public.orders rename column city to customer_city;
    end if;
    if exists (select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name='branch')
       and not exists (select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name='delivery_details') then
      alter table public.orders rename column branch to delivery_details;
    end if;
    if exists (select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name='products')
       and not exists (select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name='items') then
      alter table public.orders rename column products to items;
    end if;
    if exists (select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name='total')
       and not exists (select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name='total_amount') then
      alter table public.orders rename column total to total_amount;
    end if;

    alter table public.orders add column if not exists client_order_id text;
    alter table public.orders add column if not exists customer_email text;
    alter table public.orders add column if not exists delivery_method text default 'Нова пошта';
    alter table public.orders add column if not exists customer_comment text;
    alter table public.orders add column if not exists source text default 'website';
    alter table public.orders add column if not exists created_at timestamptz default now();
  end if;
end $$;

create unique index if not exists orders_client_order_id_key on public.orders (client_order_id);

alter table public.orders enable row level security;
grant insert on table public.orders to anon, authenticated;
grant usage, select on sequence public.orders_id_seq to anon, authenticated;

drop policy if exists "Anyone can create orders" on public.orders;
drop policy if exists "Anyone can submit a website order" on public.orders;
create policy "Anyone can submit a website order"
on public.orders for insert to anon, authenticated
with check (
  status = 'new'
  and source = 'website'
  and char_length(customer_name) between 2 and 100
  and char_length(customer_phone) between 7 and 30
  and customer_email like '%@%'
  and jsonb_array_length(items) between 1 and 30
  and total_amount >= 0
);

-- Public visitors get INSERT only; no SELECT policy is created.
