-- VA HOME v5.6 — secure reviews, verified purchases and hardened wishlist.
-- Run once in Supabase SQL Editor after the previous v5 migrations.

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  product_slug text not null,
  customer_name text not null,
  rating integer not null,
  review_text text not null,
  status text not null default 'pending',
  verified_purchase boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.reviews add column if not exists created_by uuid references auth.users(id) on delete set null;
alter table public.reviews add column if not exists reviewer_email_hash text;
alter table public.reviews add column if not exists submission_fingerprint text;

alter table public.reviews enable row level security;

-- Reviews are created only by submit-review with the service role.
revoke insert on table public.reviews from anon, authenticated;
revoke delete on table public.reviews from anon, authenticated;

drop policy if exists "Anyone can submit reviews" on public.reviews;
drop policy if exists "Public can submit pending reviews" on public.reviews;
drop policy if exists "Public can read approved reviews" on public.reviews;
create policy "Public can read approved reviews"
on public.reviews for select to anon
using (status = 'approved');

-- Signed-in customers can read approved reviews and their own pending review.
drop policy if exists "Customers can read approved and own reviews" on public.reviews;
create policy "Customers can read approved and own reviews"
on public.reviews for select to authenticated
using (status = 'approved' or created_by = auth.uid() or public.is_admin());

grant select on table public.reviews to anon, authenticated;
revoke update on table public.reviews from authenticated;
-- Admin moderation may change only status. The verified flag remains server-owned.
grant update(status) on table public.reviews to authenticated;

create index if not exists reviews_product_status_created_idx
  on public.reviews(product_slug, status, created_at desc);
create index if not exists reviews_submission_fingerprint_created_idx
  on public.reviews(submission_fingerprint, created_at desc);
create index if not exists reviews_created_by_idx
  on public.reviews(created_by, created_at desc);

-- Wishlist remains private to its owner. Explicit policies avoid accidental broad access.
alter table public.wishlists enable row level security;
drop policy if exists "Customers manage own wishlist" on public.wishlists;
drop policy if exists "Customers can read own wishlist" on public.wishlists;
drop policy if exists "Customers can add own wishlist" on public.wishlists;
drop policy if exists "Customers can delete own wishlist" on public.wishlists;
create policy "Customers can read own wishlist"
on public.wishlists for select to authenticated using (user_id = auth.uid());
create policy "Customers can add own wishlist"
on public.wishlists for insert to authenticated with check (user_id = auth.uid());
create policy "Customers can delete own wishlist"
on public.wishlists for delete to authenticated using (user_id = auth.uid());
grant select, insert, delete on table public.wishlists to authenticated;

-- Orders can only be claimed by an authenticated user whose verified JWT email matches.
create or replace function public.claim_customer_orders()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  jwt_email text := lower(coalesce(auth.jwt()->>'email', ''));
  verified_at timestamptz;
  claimed integer := 0;
begin
  if auth.uid() is null or jwt_email = '' then
    return 0;
  end if;
  select email_confirmed_at into verified_at
  from auth.users
  where id = auth.uid() and lower(email) = jwt_email;
  if verified_at is null then return 0; end if;
  update public.orders
  set customer_user_id = auth.uid()
  where customer_user_id is null and lower(customer_email) = jwt_email;
  get diagnostics claimed = row_count;
  return claimed;
end;
$$;
revoke all on function public.claim_customer_orders() from public;
grant execute on function public.claim_customer_orders() to authenticated;
