-- VA HOME v5: customer cabinet, order history and wishlist.
alter table public.orders add column if not exists customer_user_id uuid references auth.users(id) on delete set null default auth.uid();
alter table public.orders add column if not exists payment_method text not null default 'bank_transfer';
alter table public.orders drop constraint if exists orders_payment_method_check;
alter table public.orders add constraint orders_payment_method_check check(payment_method in ('bank_transfer','cash_on_delivery'));
create index if not exists orders_customer_user_idx on public.orders(customer_user_id,created_at desc);
drop policy if exists "Customers can read own orders" on public.orders;
create policy "Customers can read own orders" on public.orders for select to authenticated using (customer_user_id=auth.uid() or lower(customer_email)=lower(coalesce(auth.jwt()->>'email','')));
grant select on public.orders to authenticated;

create table if not exists public.wishlists(id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade default auth.uid(),product_slug text not null,created_at timestamptz not null default now(),unique(user_id,product_slug));
alter table public.wishlists enable row level security;
drop policy if exists "Customers manage own wishlist" on public.wishlists;
create policy "Customers manage own wishlist" on public.wishlists for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
grant select,insert,update,delete on public.wishlists to authenticated;
grant usage,select on sequence public.wishlists_id_seq to authenticated;

-- Securely attach older guest orders after the customer confirms the same email.
create or replace function public.claim_customer_orders() returns integer language plpgsql security definer set search_path=public as $$declare n integer;begin update public.orders set customer_user_id=auth.uid() where customer_user_id is null and lower(customer_email)=lower(coalesce(auth.jwt()->>'email',''));get diagnostics n=row_count;return n;end$$;
revoke all on function public.claim_customer_orders() from public;
grant execute on function public.claim_customer_orders() to authenticated;
