import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const FROM_EMAIL = "VA HOME <orders@vahome.com.ua>";
const SHOP_EMAIL = "vahome.aroma@gmail.com";
const ALLOWED = new Set(["https://vahome.com.ua","https://www.vahome.com.ua"]);
const labels: Record<string,string> = {new:"Замовлення отримано",awaiting_payment:"Очікуємо оплату",paid:"Оплату підтверджено",shipped:"Замовлення відправлено",completed:"Замовлення виконано",cancelled:"Замовлення скасовано"};
function cors(req:Request){const o=req.headers.get("origin")||"";return {"Access-Control-Allow-Origin":ALLOWED.has(o)?o:"https://vahome.com.ua","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"};}
function json(req:Request,b:unknown,s=200){return new Response(JSON.stringify(b),{status:s,headers:{...cors(req),"Content-Type":"application/json"}})}
function esc(v:unknown){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]!));}
function money(v:unknown){return `${Number(v||0).toLocaleString("uk-UA",{maximumFractionDigits:2})} грн`;}
function shell(content:string){return `<!doctype html><html lang="uk"><body style="margin:0;background:#090908;padding:20px"><div style="max-width:640px;margin:auto;border:1px solid #6b5432;background:#111;color:#f6f0e8"><div style="padding:30px;text-align:center;border-bottom:1px solid #6b5432"><div style="font:32px Georgia;letter-spacing:7px">VA HOME</div><div style="margin-top:8px;color:#d2b278;font:11px Arial;letter-spacing:4px">INVISIBLE LUXURY ATMOSPHERE</div></div><div style="padding:34px;font:16px/1.65 Arial;color:#e6ddd3">${content}</div><div style="padding:20px;text-align:center;border-top:1px solid #6b5432;color:#a99d91;font:12px Arial">vahome.com.ua · ${SHOP_EMAIL}</div></div></body></html>`}
async function resend(key:string,payload:unknown){const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify(payload)});const t=await r.text();if(!r.ok)throw new Error(`Resend ${r.status}: ${t}`);return t?JSON.parse(t):null;}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return json(req,{error:"Method not allowed"},405);try{const origin=req.headers.get("origin");if(origin&&!ALLOWED.has(origin))return json(req,{error:"Origin not allowed"},403);const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,resendKey=Deno.env.get("RESEND_API_KEY")!;const auth=req.headers.get("Authorization")||"";const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:{user},error:userError}=await userClient.auth.getUser();if(userError||!user)return json(req,{error:"Unauthorized"},401);const admin=createClient(url,service);const {data:isAdmin}=await admin.from("admin_users").select("user_id").eq("user_id",user.id).maybeSingle();if(!isAdmin)return json(req,{error:"Forbidden"},403);const body=await req.json();const orderNo=String(body.client_order_id||"").trim();const {data:o,error}=await admin.from("orders").select("*").eq("client_order_id",orderNo).single();if(error||!o)return json(req,{error:"Order not found"},404);const status=labels[o.status]||o.status;const tracking=o.tracking_number?`<div style="margin:22px 0;padding:18px;border:1px solid #6b5432"><strong>ТТН Нової пошти</strong><br><span style="font-size:20px">${esc(o.tracking_number)}</span></div>`:"";const html=shell(`<p style="margin:0;color:#d2b278;text-transform:uppercase;letter-spacing:2px;font-size:12px">${esc(o.client_order_id)}</p><h1 style="font:38px/1.15 Georgia;margin:10px 0 20px;color:#fff">${esc(status)}</h1><p>Вітаємо, ${esc(o.customer_name)}.</p>${o.status==="paid"?"<p>Оплату підтверджено. Ми готуємо ваше замовлення до відправлення.</p>":""}${o.status==="shipped"?"<p>Ваше замовлення вже передано Новій пошті.</p>":""}${o.status==="completed"?"<p>Дякуємо, що обрали VA HOME. Сподіваємося, аромат стане частиною вашого простору.</p>":""}${o.status==="cancelled"?"<p>Замовлення скасовано. Для уточнення деталей відповідайте на цей лист.</p>":""}${tracking}<p><strong>Сума замовлення:</strong> ${money(o.total_amount)}</p><p style="margin-top:28px"><a href="https://vahome.com.ua/order-status.html" style="display:inline-block;padding:14px 20px;background:#c7974d;color:#111;text-decoration:none">Перевірити статус</a></p>`);await resend(resendKey,{from:FROM_EMAIL,to:[o.customer_email],reply_to:SHOP_EMAIL,subject:`${status} — ${o.client_order_id}`,html});return json(req,{ok:true});}catch(e){console.error(e);return json(req,{error:e instanceof Error?e.message:"Unknown error"},500)}});
