-- VA HOME v15.2.0 — monobank internet acquiring
-- Adds idempotent payment attempts, signed return tokens and webhook-safe status transitions.

create extension if not exists pgcrypto;

alter table public.orders
  add column if not exists payment_provider text,
  add column if not exists payment_invoice_id text,
  add column if not exists payment_page_url text,
  add column if not exists payment_amount_minor bigint,
  add column if not exists payment_currency integer,
  add column if not exists payment_created_at timestamptz,
  add column if not exists payment_modified_at timestamptz,
  add column if not exists paid_at timestamptz,
  add column if not exists payment_failure_reason text,
  add column if not exists payment_error_code text,
  add column if not exists payment_return_token_hash text;

create unique index if not exists orders_payment_invoice_id_uidx
  on public.orders(payment_invoice_id)
  where payment_invoice_id is not null;

create table if not exists public.payment_settings (
  id text primary key,
  enabled boolean not null default false,
  provider text not null default 'monobank',
  invoice_validity_seconds integer not null default 3600 check (invoice_validity_seconds between 300 and 2592000),
  test_mode boolean not null default false,
  updated_at timestamptz not null default now()
);

insert into public.payment_settings (id, enabled, provider, invoice_validity_seconds, test_mode)
values ('card_online', false, 'monobank', 3600, false)
on conflict (id) do nothing;

create table if not exists public.payment_attempts (
  id uuid primary key default gen_random_uuid(),
  order_id bigint not null references public.orders(id) on delete cascade,
  provider text not null default 'monobank',
  invoice_id text not null unique,
  page_url text,
  reference text not null,
  amount_minor bigint not null check (amount_minor > 0),
  currency integer not null default 980,
  status text not null default 'created',
  provider_created_at timestamptz,
  provider_modified_at timestamptz,
  paid_at timestamptz,
  failure_reason text,
  error_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists payment_attempts_order_id_idx
  on public.payment_attempts(order_id, created_at desc);

create table if not exists public.payment_events (
  id bigint generated by default as identity primary key,
  payment_attempt_id uuid references public.payment_attempts(id) on delete cascade,
  order_id bigint references public.orders(id) on delete cascade,
  provider text not null default 'monobank',
  invoice_id text not null,
  provider_status text not null,
  provider_modified_at timestamptz not null,
  amount_minor bigint,
  currency integer,
  accepted boolean not null default false,
  reason text,
  payload jsonb,
  created_at timestamptz not null default now(),
  unique (invoice_id, provider_status, provider_modified_at)
);

alter table public.payment_settings enable row level security;
alter table public.payment_attempts enable row level security;
alter table public.payment_events enable row level security;

drop policy if exists "Admins can read payment settings" on public.payment_settings;
create policy "Admins can read payment settings"
on public.payment_settings for select to authenticated
using ((select public.is_admin()));

drop policy if exists "Admins can update payment settings" on public.payment_settings;
create policy "Admins can update payment settings"
on public.payment_settings for update to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "Admins can read payment attempts" on public.payment_attempts;
create policy "Admins can read payment attempts"
on public.payment_attempts for select to authenticated
using ((select public.is_admin()));

drop policy if exists "Admins can read payment events" on public.payment_events;
create policy "Admins can read payment events"
on public.payment_events for select to authenticated
using ((select public.is_admin()));

create or replace function public.apply_monobank_payment_status(
  p_invoice_id text,
  p_status text,
  p_amount_minor bigint,
  p_currency integer,
  p_reference text,
  p_created_at timestamptz,
  p_modified_at timestamptz,
  p_failure_reason text default null,
  p_error_code text default null,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_attempt public.payment_attempts%rowtype;
  v_order public.orders%rowtype;
  v_event_time timestamptz := coalesce(p_modified_at, p_created_at, now());
  v_payment_status text;
  v_notify_paid boolean := false;
  v_current_time timestamptz;
  v_reason text;
begin
  select * into v_attempt
  from public.payment_attempts
  where invoice_id = p_invoice_id
  for update;

  if not found then
    insert into public.payment_events (
      provider, invoice_id, provider_status, provider_modified_at,
      amount_minor, currency, accepted, reason, payload
    ) values (
      'monobank', coalesce(p_invoice_id, ''), coalesce(p_status, 'unknown'), v_event_time,
      p_amount_minor, p_currency, false, 'INVOICE_NOT_FOUND', coalesce(p_payload, '{}'::jsonb)
    ) on conflict do nothing;
    return jsonb_build_object('applied', false, 'reason', 'INVOICE_NOT_FOUND');
  end if;

  select * into v_order
  from public.orders
  where id = v_attempt.order_id
  for update;

  if not found then
    return jsonb_build_object('applied', false, 'reason', 'ORDER_NOT_FOUND');
  end if;

  if p_amount_minor is distinct from v_attempt.amount_minor
     or p_currency is distinct from v_attempt.currency
     or coalesce(p_reference, '') <> v_attempt.reference then
    v_reason := 'PAYMENT_MISMATCH';
    insert into public.payment_events (
      payment_attempt_id, order_id, provider, invoice_id, provider_status,
      provider_modified_at, amount_minor, currency, accepted, reason, payload
    ) values (
      v_attempt.id, v_order.id, 'monobank', p_invoice_id, coalesce(p_status, 'unknown'),
      v_event_time, p_amount_minor, p_currency, false, v_reason, coalesce(p_payload, '{}'::jsonb)
    ) on conflict do nothing;
    return jsonb_build_object('applied', false, 'reason', v_reason, 'order_id', v_order.id);
  end if;

  v_current_time := coalesce(v_attempt.provider_modified_at, '-infinity'::timestamptz);
  if v_event_time < v_current_time then
    insert into public.payment_events (
      payment_attempt_id, order_id, provider, invoice_id, provider_status,
      provider_modified_at, amount_minor, currency, accepted, reason, payload
    ) values (
      v_attempt.id, v_order.id, 'monobank', p_invoice_id, coalesce(p_status, 'unknown'),
      v_event_time, p_amount_minor, p_currency, false, 'STALE_EVENT', coalesce(p_payload, '{}'::jsonb)
    ) on conflict do nothing;
    return jsonb_build_object('applied', false, 'reason', 'STALE_EVENT', 'order_id', v_order.id);
  end if;

  if v_order.payment_status = 'paid' and p_status not in ('success', 'reversed', 'refunded') then
    insert into public.payment_events (
      payment_attempt_id, order_id, provider, invoice_id, provider_status,
      provider_modified_at, amount_minor, currency, accepted, reason, payload
    ) values (
      v_attempt.id, v_order.id, 'monobank', p_invoice_id, coalesce(p_status, 'unknown'),
      v_event_time, p_amount_minor, p_currency, false, 'PAID_ORDER_NOT_DOWNGRADED', coalesce(p_payload, '{}'::jsonb)
    ) on conflict do nothing;
    return jsonb_build_object('applied', false, 'reason', 'PAID_ORDER_NOT_DOWNGRADED', 'order_id', v_order.id);
  end if;

  v_payment_status := case
    when p_status = 'success' then 'paid'
    when p_status in ('failure', 'failed') then 'failed'
    when p_status = 'expired' then 'expired'
    when p_status in ('reversed', 'refunded') then 'refunded'
    else 'pending'
  end;

  v_notify_paid := p_status = 'success' and coalesce(v_order.payment_status, '') <> 'paid';

  update public.payment_attempts
  set status = coalesce(p_status, status),
      provider_created_at = coalesce(p_created_at, provider_created_at),
      provider_modified_at = greatest(coalesce(provider_modified_at, v_event_time), v_event_time),
      paid_at = case when p_status = 'success' then coalesce(paid_at, v_event_time) else paid_at end,
      failure_reason = case when p_status in ('failure', 'failed', 'expired') then nullif(p_failure_reason, '') else null end,
      error_code = case when p_status in ('failure', 'failed', 'expired') then nullif(p_error_code, '') else null end,
      updated_at = now()
  where id = v_attempt.id;

  update public.orders
  set payment_provider = 'monobank',
      payment_invoice_id = case
        when p_status = 'success' then p_invoice_id
        when payment_invoice_id is null then p_invoice_id
        else payment_invoice_id
      end,
      payment_amount_minor = v_attempt.amount_minor,
      payment_currency = v_attempt.currency,
      payment_created_at = coalesce(payment_created_at, p_created_at, v_attempt.created_at),
      payment_modified_at = greatest(coalesce(payment_modified_at, v_event_time), v_event_time),
      payment_status = v_payment_status,
      paid_at = case when p_status = 'success' then coalesce(paid_at, v_event_time) else paid_at end,
      payment_failure_reason = case when v_payment_status in ('failed', 'expired') then nullif(p_failure_reason, '') else null end,
      payment_error_code = case when v_payment_status in ('failed', 'expired') then nullif(p_error_code, '') else null end,
      status = case
        when p_status = 'success' and status in ('new', 'awaiting_payment') then 'paid'
        when v_payment_status in ('pending', 'failed', 'expired') and status = 'new' then 'awaiting_payment'
        else status
      end,
      updated_at = now()
  where id = v_order.id;

  insert into public.payment_events (
    payment_attempt_id, order_id, provider, invoice_id, provider_status,
    provider_modified_at, amount_minor, currency, accepted, reason, payload
  ) values (
    v_attempt.id, v_order.id, 'monobank', p_invoice_id, coalesce(p_status, 'unknown'),
    v_event_time, p_amount_minor, p_currency, true, 'APPLIED', coalesce(p_payload, '{}'::jsonb)
  ) on conflict do nothing;

  return jsonb_build_object(
    'applied', true,
    'order_id', v_order.id,
    'client_order_id', v_order.client_order_id,
    'payment_status', v_payment_status,
    'notify_paid', v_notify_paid
  );
end;
$$;

revoke all on function public.apply_monobank_payment_status(text,text,bigint,integer,text,timestamptz,timestamptz,text,text,jsonb) from public, anon, authenticated;
grant execute on function public.apply_monobank_payment_status(text,text,bigint,integer,text,timestamptz,timestamptz,text,text,jsonb) to service_role;
